### PR TITLE
actionNotifications -> main question_difficulty

### PR DESCRIPTION
**Pull request by Hamarius**
A question difficulty picker is now shown before the question panel.

### CODE REVIEW

**Review by ubeF — CHANGES_REQUESTED** [review]
Difficulty Menu is displayed behind the map

**Review by ubeF — CHANGES_REQUESTED** [review]
They options are now displayed correctly, but the hitbox of the "schwer" option is still covered by the map and can't be clicked in spots, where the option covers the map

**Comment by Hamarius** [comment]
tbh I dont really get it with the layers, I tried everything I could think of now but nothing improves it.

**Comment by hfxbse** [comment]
> tbh I don't really get it with the layers, I tried everything I could think of now but nothing improves it.

Did not have a look yet but do you not use a canvas as your root element for the picker? No other dialog seems to have any problem by doing so.

A side note to the pull request title: Please change it to be more descriptive, and continue to do so in the future

**Comment by Hamarius** [comment]
Thanks! That did the trick, now it seems to work.

**Review by ubeF — APPROVED** [review]
Tbh i didn't read all these changes but it seems to work, so i'll just trust you with that

**Pull request merged**
