### PR TITLE
Add patent office

### PR DESCRIPTION
**Pull request by grxver7**

### CODE REVIEW

**Comment by ubeF** [comment]
According to the rules, the player can choose how many "patente" to buy:
- [x] Add entry-field for the amount of "patente" to buy
- [x] check if the player has enough money for the transaction
- [x] Optional: Display the amount the player already has of each currency somewhere in the menu
- [x] Add an awaitable function the field can call on this menu. this way the player can be passed to the menu (Necessary for checking money of the player)

**Comment by grxver7** [comment]
Changes see under commit:
image

Signals and minimal logic should still be included

**Comment by hfxbse** [comment]
As a heads-up before reviewing, you should use a canvas as your root node type.

**Comment by KevinBasener** [comment]
Should be done

**Review by ubeF — CHANGES_REQUESTED** [review]
Looking good. just 2 small problems:
- The dice doesn't display anything in this branch (probably because of those old commits. remove the ones you don't need
- Why is there an unused scene "patent_office/patent_office_decide_interaction.tscn". It's not necessary in my opinion. just remove those files

**Comment by KevinBasener** [comment]
> Looking good. just 2 small problems:
> 
> * The dice doesn't display anything in this branch (probably because of those old commits. remove the ones you don't need
> * Why is there an unused scene "patent_office/patent_office_decide_interaction.tscn". It's not necessary in my opinion. just remove those files

Rebased it

**Review by ubeF — APPROVED** [review]

**Pull request merged**
