### PR TITLE
Integration question panel

### PR DESCRIPTION
**Pull request by tuke307**
TODO: move question panel instanciating code to the right position

### CODE REVIEW

**Review by ubeF — CHANGES_REQUESTED** [review]
After hitting submit, the question-panel should display if the answer was correct or not (maybe with green and red highlighting) and maybe time-out for a few seconds so the player has time to view the result, before the signal is sent and the caller destroys the question-panel

**Comment by tuke307** [comment]
not beautiful, but functional lol
(TODO: dont override the theme style, after submitting, because the user cant see the selected answer anymore)

**Comment by hfxbse** [comment]
> (TODO: don't override the theme style, after submitting, because the user can't see the selected answer anymore)

I believe the user cannot see their selected answer simply because the button loses focus when clicking on another. Maybe a [button group that behaves like radio buttons](https://docs.godotengine.org/en/stable/classes/class_buttongroup.html) could help, but I did not investigate further.

**Review by ubeF — CHANGES_REQUESTED** [review]
Connecting the panel to the question field doesnt seem to work like intended:
- Panel behind map
- Not centered

**Comment by tuke307** [comment]
not sure how to center the question panel, related to the player camera. i tried setting the size and position related to the current viewport, but that doesnt really work.
```
        var currentView = get_viewport().get_visible_rect()
	var center = currentView.get_center()
	
	question_panel.set_size(Vector2(currentView.size.x/2, currentView.size.y/2))
	question_panel.set_position(Vector2(center.x - 1000/2, center.y - 500/2))
```

**Comment by ubeF** [comment]
It works on the dice_roll. Might wanna check out, how it's implemented there

**Comment by hfxbse** [comment]
> not sure how to center the question panel, related to the player camera. I tried setting the size and position related to the current viewport, but that doesn't really work.

The easiest way to do that might be to change your root node to a canvas and anchor it to the center of the screen. This technique is already used for other elements like the camera button or the dice panel.

**Comment by KevinBasener** [comment]
> > not sure how to center the question panel, related to the player camera. I tried setting the size and position related to the current viewport, but that doesn't really work.
> 
> The easiest way to do that might be to change your root node to a canvas and anchor it to the center of the screen. This technique is already used for other elements like the camera button or the dice panel.

Fixed it

**Review by ubeF — APPROVED** [review]

**Pull request merged**
