### PR TITLE
Create map layout

### PR DESCRIPTION
**Pull request by hfxbse**
Sets up a map layout.

Things that need to be done before merging:

- [x] Add bidirectional fields, which are rounded. #22 proposes a possible implementation.
- [x] Theme particular fields as required. Depend on the completion of #18.

### CODE REVIEW

**Comment by ubeF** [comment]
The Map is still missing the round fields. Or is that a display error on my side?

**Comment by hfxbse** [comment]
> The Map is still missing the round fields. Or is that a display error on my side?

They should be there, I just double-checked. Did you pull the newest version? Reloading the project afterward could also help.

**Comment by ubeF** [comment]
> > The Map is still missing the round fields. Or is that a display error on my side?
> 
> They should be there, I just double-checked. Did you pull the newest version? Reloading the project afterward could also help.

Ok, they are displaying now

**Comment by ubeF** [comment]
When pressing "Undo-Back-Undo" the player moves back an arbitrary amount of fields and gets stuck there. Highly unlikely to happen during normal game-play and probably an old issue, so not change-request-worthy, but something to keep in mind

**Review by ubeF — APPROVED** [review]

**Comment by hfxbse** [comment]
> When pressing "Undo-Back-Undo" the player moves back an arbitrary amount of fields and gets stuck there. Highly unlikely to happen during normal game-play and probably an old issue, so not change-request-worthy, but something to keep in mind

Oh I'm pretty sure it moves back till it reached the last saved transversed field by looking at the implementation of the undo function. That's definitely an old issue which caused an endless loop before. Could be fixed but not sure what behavior is expected in that case.

**Pull request merged**
